### ISSUE TITLE
about plotting

### ISSUE THREAD

**Issue by XuexueLiu** [dportik/dadi_pipeline#1]
Dear dportik
 I used the example data of two populations, with the command "python dadi_2D_04_plotting_functions.py",  and got the result:
Traceback (most recent call last):
  File "dadi_2D_04_plotting_functions.py", line 373, in <module>
    vic_no_mig = Optimize_Functions.Optimize_Single(pts, fs, "vic_no_mig", vic_no_mig_params)
  File "/home/data/dadi_new/dadi_pipeline-master/Two_Populations/Optimize_Functions.py", line 6906, in Optimize_Single
    sim_model = func_exec(params, fs.sample_sizes, pts)
  File "/home/share/software/anaconda2/lib/python2.7/site-packages/dadi-1.6.3-py2.7-linux-x86_64.egg/dadi/Numerics.py", line 261, in extrap_func
    result_l = map(partial_func, pts_l)
  File "/home/data/dadi_new/dadi_pipeline-master/Two_Populations/Models_2D.py", line 564, in vic_no_mig
    nuA, nu1, nu2, T, s = params
ValueError: need more than 0 values to unpack
I donot know what's wrong with this software.
thankyou!

**Comment by dportik** [comment]
Hello,
This error is because no parameter values have been supplied for that
model. Look at line 235, this is where the values should be. Notice the
list is empty (compare to parameter sets above). In the example data I
provided I did not run these models. You will supply your own values for
your data if you run the island model set. It will work if values are
written in.


Daniel Portik, PhD
Postdoctoral Researcher
Department of Ecology and Evolution
University of Arizona
P.O. Box 210088
Tucson, AZ 85721
danielportik@email.arizona.edu <daniel.portik@uta.edu>

**Comment by XuexueLiu** [comment]
Dear Daniel Portik
 Thankyou for your reply, I use my own data and add all the parameters, while I got the result:
QXcbConnection: Could not connect to display 
Aborted (core dumped)
is there something wrong with the software, I used. thankyou !

**Comment by dportik** [comment]
Hello,
This sounds like an issue with the python package matplotlib. I would
ensure that all the dependencies are installed, updated, and try again. If
the issue persists I suggest you look at the support material for
matplotlib.

Daniel Portik, PhD
Postdoctoral Researcher
Department of Ecology and Evolution
University of Arizona
P.O. Box 210088
Tucson, AZ 85721
danielportik@email.arizona.edu <daniel.portik@uta.edu>
