### ISSUE TITLE
AIC 

### ISSUE THREAD

**Issue by zhangleigloria** [dportik/dadi_pipeline#12]
Dear Mr.Daniel,
         I am sorry to bother you in your busy schedule. When I run the script 'dadi_Run_2D_Set.py' , the result file 'optimized.txt' shows:
 log-likelihood  AIC     chi-squared     theta   optimized_params(nu1, nu2, T)
 0.0     nan     nan     0.0     0.3052, 0.1408, 0.2376.
        The AIC value is nan , but I can not find the reason why it is. The optimized params  have numerical values. I checked the data and didn't find the problem. Could you tell me about it?

**Comment by dportik** [comment]
Before I can attempt to provide any explanation, you'll need to provide me with more information.

Was this conducted with the provided example data, or with your own data set? 

Are you using the newest version of dadi (designed for Python3)?  

During runs, sometimes this message appears for a replicate: "WARNING:Numerics:Extrapolation may have failed. Check resulting frequency spectrum for unexpected results." If so, the values for the log-likelihood (and consequently AIC) are unreliable. Did you see this message on screen at all?

**Comment by zhangleigloria** [comment]
Thank you for you reply! 

This was conducted with my own data set. I used the previous version( designed for Python2.7).

Yes, I did. This warning appeared in my results.

Do I need to change it to the latest version(designed for Python3)?

**Comment by dportik** [comment]
You should be fine using the Python 2.7 version. The optimizations sometimes fail due to a variety of reasons. If you see the error message many times for a particular model, it may be that the parameters are reaching the bounds, or the model is very complex and difficult to fit. If you only occasionally see the message, then it can be ignored. However, I again emphasize that those replicates will produce unreliable log-likelihoods and parameter values, and those replicates should be removed from your results.

**Comment by dportik** [comment]
The pipeline (v3.1) is now Python3 compatible and will only work with dadi v2+. You may want to try running your analyses with these newest versions to be sure. If the errors persist, please let me know.

I should also mention that the `Summarize_Outputs.py` script (in the 2D and 3D pipeline folders) has been updated so that any results with a `nan` character in the rows will automatically be excluded from the final results summary. So if your results for a model contain a mix of some bad runs and otherwise mostly good runs, they won't crash the summary script.
