### ISSUE TITLE
Summarize_Outputs.py

### ISSUE THREAD

**Issue by pstokespmb** [dportik/dadi_pipeline#3]
Hey @dportik!

Thanks for making these pipelines! As someone who is very new to python, these pipelines are very helpful for use of dadi! I am receiving an error when I run: python2 Summarize_Outputs.py

"
Examining file WILD_LANDRACE.asym_mig.optimized.txt
Traceback (most recent call last):
  File "Summarize_Outputs.py", line 59, in <module>
    content.sort(key=lambda x: float(x[3]))
  File "Summarize_Outputs.py", line 59, in <lambda>
    content.sort(key=lambda x: float(x[3]))
ValueError: could not convert string to float: AIC
"

Could you please explain what is going on?

Also, have you created a script that allows the inclusion of ancestral states? I noticed the scripts were all set up to be folded, but I do have ancestral state information for each site I am using.

**Comment by dportik** [comment]
Hello,
I'm happy to hear you have found them to be useful, thank you for your feedback.

It appears that the file 'WILD_LANDRACE.asym_mig.optimized.txt' has some type of formatting error. Did you stop and restart the analysis, or did it end prematurely? I would open this file and ensure that the first line contains the appropriate headers (Model, Replicate, log-likelihood, AIC, chi-squared, theta, optimized_params(labels) ), and that all other lines contain only results. The error was thrown because the string 'AIC' appeared beyond the first line, and this column should only have numbers. Please ensure that your file has the correct format and try again. If the problem persists, please let me know.

The allele frequency spectra do not need to be folded. If you have outgroup information you can change this easily in the script where the spectrum object is created, by setting the 'polarized' argument to True. 

`fs = dadi.Spectrum.from_data_dict(dd, pop_ids=pop_ids, projections = proj, polarized = False)
#change this to:
fs = dadi.Spectrum.from_data_dict(dd, pop_ids=pop_ids, projections = proj, polarized = True)`

**Comment by pstokespmb** [comment]
Hey!

Thanks for the reply!

WRT Q1, I will look into that, for now I simply searched for the most positive negative log likelihood.

WRT Q2, thanks! This is what I suspected, but I ended up just looking at the folded first because I thought changing polarized = False to polarized = True was too easy of a solution!

Thanks for your help!

One more question. One of the optimizations took upwards of 23 hours to complete on my local machine. Is there any way to make this go faster without using a cluster (UC Berkeley's cluster is quite finicky with self installed software)

**Comment by pstokespmb** [comment]
I am able to run the program when polarized = False, but when setting polarized = True I get the following error.

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dadi-1.7.0-py2.7-macosx-10.9-x86_64.egg/dadi/Numerics.py:171: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
Traceback (most recent call last):
  File "dadi_Run_2D_Set.py", line 249, in <module>
    Optimize_Functions.Optimize_Routine(fs, pts, prefix, "asym_mig_twoepoch", Models_2D.asym_mig_twoepoch, rounds, 8, reps=reps, maxiters=maxiters, folds=folds, param_labels = "nu1, nu2, m12a, m21a, m12b, m21b, T1, T2")
  File "/Users/peterstokes/Documents/Science/Blackman_Lab/dadi/dadi_data/Optimize_Functions.py", line 237, in Optimize_Routine
    rep_results = collect_results(fs, sim_model, params_opt, roundrep)
  File "/Users/peterstokes/Documents/Science/Blackman_Lab/dadi/dadi_data/Optimize_Functions.py", line 121, in collect_results
    chi2 = numpy.sum((folded_sim_model - fs)**2/folded_sim_model)
  File "<string>", line 3, in __sub__
  File "build/bdist.macosx-10.9-x86_64/egg/dadi/Spectrum_mod.py", line 1878, in _check_other_folding
ValueError: Cannot operate with a folded Spectrum and an unfolded one.


Do you see anything that would cause errors in the first bit of my script?

#===========================================================================
# Import data to create joint-site frequency spectrum
#===========================================================================

#**************
snps = "/Users/peterstokes/Documents/Science/Blackman_Lab/dadi/dadi_data/python_scripts/angsd_joined_LRW_60_REF_ANC_included_ready.txt"

#Create python dictionary from snps file
dd = dadi.Misc.make_data_dict(snps)

#**************
#pop_ids is a list which should match the populations headers of your SNPs file columns
pop_ids=["WILD", "LANDRACE"]

#**************
#projection sizes, in ALLELES not individuals
proj = [14,14]

#Convert this dictionary into folded AFS object
#[polarized = False] creates folded spectrum object
fs = dadi.Spectrum.from_data_dict(dd, pop_ids=pop_ids, projections = proj, polarized = True)

#print some useful information about the afs or jsfs
print "\n\n============================================================================\nData for site frequency spectrum\n============================================================================\n"
print "projection", proj
print "sample sizes", fs.sample_sizes
sfs_sum = numpy.around(fs.S(), 2)
print "Sum of SFS = ", sfs_sum, '\n', '\n'

#================================================================================
# Calling external 2D models from the Models_2D.py script
#================================================================================
'''
 We will use a function from the Optimize_Functions.py script for our optimization routines:
 
 Optimize_Routine(fs, pts, outfile, model_name, func, rounds, param_number, reps=None, maxiters=None, folds=None, in_params=None, in_upper=None, in_lower=None, param_labels=" ")
 
   Mandatory Arguments =
    fs:  spectrum object name
    pts: grid size for extrapolation, list of three values
    outfile:  prefix for output naming
    model_name: a label to help label the output files; ex. "no_mig"
    func: access the model function from within 'moments_Run_Optimizations.py' or from a separate python model script, ex. after importing Models_2D, calling Models_2D.no_mig
    rounds: number of optimization rounds to perform
    param_number: number of parameters in the model selected (can count in params line for the model)
   Optional Arguments =
     reps: a list of integers controlling the number of replicates in each of the optimization rounds
     maxiters: a list of integers controlling the maxiter argument in each of the optimization rounds
     folds: a list of integers controlling the fold argument when perturbing input parameter values
     in_params: a list of parameter values 
     in_upper: a list of upper bound values
     in_lower: a list of lower bound values
     param_labels: list of labels for parameters that will be written to the output file to keep track of their order
Below, I give all the necessary information to call each model available in the
Models_2D.py script. I have set the optimization routine to be the same for each
model using the optional lists below, which are included as optional arguments for
each model. This particular configuration will run 4 rounds as follows:
Round1 - 10 replicates, maxiter = 3, fold = 3
Round2 - 20 replicates, maxiter = 5, fold = 2
Round3 - 30 replicates, maxiter = 10, fold = 2
Round4 - 40 replicates, maxiter = 15, fold = 1
If this script was run as is, each model would be called and optimized sequentially;
this could take a very long time. For your actual analyses, I strongly recommend
creating multiple scripts with only a few models each and running them
independently. It is also not a good idea to mix models from the Diversification Set
and the Island Set, as each was meant to be mutually exclusive.
'''


#create a prefix based on the population names to label the output files
#ex. Pop1_Pop2
prefix = "_".join(pop_ids)

#**************
#make sure to define your extrapolation grid size (based on your projections)
pts = [50,60,70]

#**************
#Set the number of rounds here
rounds = 4

#define the lists for optional arguments
#you can change these to alter the settings of the optimization routine
reps = [10,20,30,40]
maxiters = [3,5,10,15]
folds = [3,2,2,1]

**Comment by dportik** [comment]
I see the problem - it's nothing on your end. The issue relates to how the chi-squared test statistic is calculated. I will work on getting this fixed, and will post when it is completed (soon!).

Some models take longer than other to run, there isn't a simple way to speed this up. One thing I have done is to duplicate the scripts and divide up the models to run among scripts, then execute a script for every core I have available. If you know a certain model will take longer you can run this on one core in its own script and run the other models using a second script. This will certainly save you time rather than running all models and optimizations in a linear fashion.

**Comment by dportik** [comment]
I've gone ahead and updated the pipeline to fix the problem. You'll need to re-download all the scripts as they all have been changed to include an additional feature.

You will now need to specify whether the spectrum object is folded or unfolded in the optimization function.  To change whether the frequency spectrum is folded vs. unfolded requires two changes in the script. The first is where the spectrum object is created, indicated by the *polarized* argument:
 
     `#Convert this dictionary into folded AFS object
     #[polarized = False] creates folded spectrum object
     fs = dadi.Spectrum.from_data_dict(dd, pop_ids=pop_ids, projections = proj, polarized = False)`

The above code will create a folded spectrum. When calling the optimization function, this must also be indicated in the *fs_folded* argument:

     `#for example:
     Optimize_Functions.Optimize_Routine(fs, pts, prefix, "sym_mig", sym_mig, 3, 4, fs_folded=True)`
     
To create an unfolded spectrum, the *polarized* and *fs_folded*  arguments in the above lines need to be changed accordingly:

     `#[polarized = True] creates an unfolded spectrum object
     fs = dadi.Spectrum.from_data_dict(dd, pop_ids=pop_ids, projections = proj, polarized = True)
     
     #and the optimization routine function must also be changed:
     Optimize_Functions.Optimize_Routine(fs, pts, prefix, "sym_mig", sym_mig, 3, 4, fs_folded=False)`
     
It will be clear if either argument has been misspecified because the calculation of certain statistics will cause a crash with the following error:

     `ValueError: Cannot operate with a folded Spectrum and an unfolded one.`

If you see this, check to make sure both relevant arguments actually agree on the spectrum being folded or unfolded.

These instruction will appear on the main page and apply to the 2D and 3D pipelines too. Please let me know if you have any trouble running the updated scripts with the unfolded spectrum!

**Comment by dportik** [comment]
I've gone ahead and opened a new issue for the folded vs. unfolded spectrum, and the solution has been posted and all code is updated.

**Comment by pstokespmb** [comment]
Thank you so much for fixing this!
