### ISSUE TITLE
Question about theta, Nref, and nuA

### ISSUE THREAD

**Issue by joannarifkin** [dportik/dadi_pipeline#5]
Hi there,

Thanks for writing this pipeline - I find it incredibly helpful! I'm trying to interpret my results from the island models and I'm having trouble with the relationship between the Nref estimated from theta - which, as I understand it from the dadi-users Google group, is generally the ancestral population - and nuA. What Nref is nuA defined in relation to? 

Thanks,

JR

**Comment by dportik** [comment]
Hello,
Thank you for the feedback, I'm glad to hear the scripts are working well and helping you to accomplish your research goals! 

I wrote the island models in a way that allowed me to restrict the origin of the island population with better control vs. a more general splitting model. For example, it wouldn't make as much sense to allow the island and mainland population to take any size following the split - this could allow unreasonable scenarios in which the island population is huge and the mainland population is tiny. 

To enforce something more reasonable, I labeled the mainland + island source population as nuA, and represented the mainland population (pop 1) as nu1 = nuA*(1-s) and the island population (pop 2) as nu2 = nuA*(s). Here, the variable s ranges from 0-1 and indicates the proportion of nuA that became nu1 or became nu2. I restrict the value of s to be < 0.5 in all the island models by supplying an upper limit parameter bounds, such that the island population is never more than 50% of the original nuA, and the mainland is never less than 50% of the original nuA. 

To find out the value of nuA, you will need to do the same calculation as you would for any of the population estimates - scale by the Nref: 
nuA*Nref = actual population size of nuA
nu1*Nref = actual population size of nu1
nu2*Nref = actual population size of nu2

The Nref is calculated by the following equation:

Theta = 4 * Nref * mu * L

- Theta is estimated by dadi and written to the main output files as part of this pipeline
- mu refers to the mutation rate (specific to your system or a best guess)
- L is the total length of DNA sequence (in bp) that was analyzed in order to obtain the SNP data

Please let me know if this clarifies things, and if you have any additional questions.

Best,
Dan

**Comment by joannarifkin** [comment]
Hi Dan,

Thank you, that's extremely helpful. If I understand correctly, I can basically think of Nref solely as a scaling factor and not as an additional estimate of population size, yes?

Thanks again!

Joanna

**Comment by dportik** [comment]
Hi Joanna,
The Nref is always the ancestral population size, but is also used to transform the unscaled population sizes from the models into actual population sizes. In the case of the island models, nuA is more or less a way to track the splitting of the mainland and island populations, and wasn't a parameter I was explicitly interested in. I was more interested in estimating s, nu1, nu2, and any of the migration or admixture parameters. The Nref will still be the ancestral population size, and nuA might be larger or smaller than this. If the unscaled value of nuA is close to 1, then it will be very similar to Nref, but this doesn't have to be true. Does that make sense?

**Comment by joannarifkin** [comment]
Hi Dan,

Yep, that makes sense. Thanks again for the speedy and detailed response.

Cheers,

Joanna
